### PR TITLE
minor enhancement

### PR DESCRIPTION
**Pull request by Sispheor**
Hi, thanks for your exporter. I've updated a couple thing. I don't know if you are interested by implementing them into your project.

- refactor the code to accept only http call like a backbox exporter
- code hardening/cleanup
- add Prometheus config example
- add labels: product_name and server_name. 
- endpoint can be precised. default to /metrics
- add firmware version gauge

### CODE REVIEW

**Comment by Sispheor** [comment]
up ! :)

**Comment by Rucknar** [comment]
@joeds13 One for you Joe!

**Comment by Sispheor** [comment]
It's just because I just received a [PR on my fork](https://github.com/Sispheor/hpilo-exporter/pull/1). I think it would be better if you keep the lead on the project.

**Comment by fredericve** [comment]
I tested this PR on a number of our servers. Seems to work fine! thanks.

**Pull request merged**
